apiVersion: eksctl.io/v1alpha5
kind: Clusterconfig

metadata:
   name: roboshop
   region: us-east-1

managedNodeGroups:
   - name: spot
     instanceType: t2,micro
     desiredCapacity: 3
     spot: true